### ISSUE TITLE
Deeper CLI Packages

### ISSUE THREAD

**Issue by SpeedForceGN** [Kav91/deeper-connect-monitoring#1]
As I try to download/install "deeper-cli-windows-x86_64-0.1.3.zip", I continue to receive an error that page is unavailable. Even after I have added the three addresses to whitelist.

**Comment by Kav91** [comment]
Hi @SpeedForceGN whitelisting is not needed for the download, the packages are hosted by amazon, can you try  clicking or pasting the full address into your browser address bar instead?

https://deeper-network.s3.amazonaws.com/deeper-cli/deeper-cli-windows-x86_64-0.1.3.zip

**Comment by SpeedForceGN** [comment]
I tried the link above in two browsers and also PRIVATE BROWSER MODE. Continue to "This site can’t be reached"

**Comment by SpeedForceGN** [comment]
When installing RELIC, I also selected in LOGS. Is there a way to remove?

**Comment by SpeedForceGN** [comment]
Well Holy Shiznits.  No matter what I did on my laptop, I couldn't down load the fill.  Well I just was able to down load it with my android phone

**Comment by SpeedForceGN** [comment]
well now I cant get the .exe to install.  Also when I get to the Move the logging configuration file, and follow the steps, the directory is blank.  I dont know what is going on and to do

**Comment by SpeedForceGN** [comment]
How do I know if RELIC is installed properly? I dont think it did, because I dont see it in my programs. Can be seen in browser. What directory for CLI?  How to undo what has been done so that I can try again?  My laptop continues to to me that I dont have permissions or am admin. Fix?   cant upload photos. github is telling something is wrong and will not allow uploads

**Comment by SpeedForceGN** [comment]
I didnt close this

**Comment by Kav91** [comment]
If you're not an administrator on your laptop to run the commands and install the programs then you won't be able to proceed. 

Also if you can't upload screenshots to GitHub which is a public site it sounds like you have something on your laptop restricting what you can do. 

Even as you mentioned before your issue about downloading the CLI package, sounds like something on your laptop is blocking you.

**Comment by Kav91** [comment]
I'm based in Sydney.

Can you confirm if you can run powershell as an administrator?
Search powershell in windows, then right click and click run as administrator.

![image](https://user-images.githubusercontent.com/13043208/136678752-0d270b61-6e9c-4f93-a639-c29c7037dcc9.png)

**Comment by SpeedForceGN** [comment]
YES, Power Shell admin everytime

**Comment by SpeedForceGN** [comment]
I am using brave brower.

**Comment by Kav91** [comment]
I would recommend using Chrome or Firefox to eliminate that as a potential issue.

However Brave browser has nothing to do with the above steps I mentioned to try. Can you please try what was mentioned above first.
